export enum ScientificFunction {
  Sin = 'sin',
  Cos = 'cos',
  Tan = 'tan',
  Asin = 'asin',
  Acos = 'acos',
  Atan = 'atan',
  Sqrt = 'sqrt',
  Square = 'x²',
  Cube = 'x³',
  Power = 'xʸ',
  TenPower = '10ˣ',
  Exp = 'eˣ',
  Ln = 'ln',
  Log = 'log',
  Pi = 'π',
  Euler = 'e',
  Abs = 'abs',
  Factorial = 'n!',
  Mod = 'mod',
  Rand = 'Rand',
  InvExp = 'exp',
  OpenParen = '(',
  CloseParen = ')',
}
